import type { Device, Camera, Alert } from './types';

export const dummyDevices: Device[] = [
  {
    alias: 'Ewe-17',
    deviceId: '001',
    type: 'collar',
    status: 'online',
    batteryV: 3.87,
    ranch: 'North Pasture',
    lat: 40.5853,
    lon: -105.0844,
    fwVersion: '0.9.3',
    rssi: -78,
  },
  {
    alias: 'Ram-02',
    deviceId: '002',
    type: 'collar',
    status: 'online',
    batteryV: 3.72,
    ranch: 'South Range',
    lat: 40.5861,
    lon: -105.0857,
    fwVersion: '0.9.2',
    rssi: -71,
  },
  {
    alias: 'Calf-11',
    deviceId: '003',
    type: 'collar',
    status: 'offline',
    batteryV: 3.41,
    ranch: 'South Range',
    lat: 40.5848,
    lon: -105.082,
    fwVersion: '0.9.1',
    rssi: -99,
  },
  {
    alias: 'Ewe-33',
    deviceId: '004',
    type: 'collar',
    status: 'online',
    batteryV: 3.95,
    ranch: 'North Pasture',
    lat: 40.5859,
    lon: -105.083,
    rssi: -75,
  },
  {
    alias: 'Relay-01',
    deviceId: '005',
    type: 'relay',
    status: 'online',
    batteryV: 4.1,
    ranch: 'North Pasture',
    lat: 40.5865,
    lon: -105.086,
    rssi: -65,
  },
  {
    alias: 'Tower-01',
    deviceId: '006',
    type: 'tower',
    status: 'online',
    batteryV: 5.0,
    ranch: 'North Pasture',
    lat: 40.585,
    lon: -105.0868,
    rssi: -55,
  },
];

export const dummyCameras: Camera[] = [
  {
    id: 'cam-1',
    name: 'North Gate Cam',
    lat: 40.5856,
    lon: -105.0848,
    radiusM: 150,
    rssi: -62,
    feedUrl: '',
    note: 'Facing north gate',
  },
  {
    id: 'cam-2',
    name: 'South Creek Cam',
    lat: 40.585,
    lon: -105.0829,
    radiusM: 200,
    rssi: -78,
    feedUrl: '',
    note: 'Creek crossing',
  },
  {
    id: 'cam-3',
    name: 'Barn NW Cam',
    lat: 40.5864,
    lon: -105.0859,
    radiusM: 120,
    rssi: -70,
    feedUrl: '',
    note: 'Barn approach',
  },
];

export const dummyAlerts: Alert[] = [
  {
    id: 'alrt-1',
    severity: 'P0',
    deviceId: 'abc123',
    alias: 'Ewe-17',
    kind: 'predator_detected',
    confidence: 0.92,
    ts: new Date().toISOString(),
    acked: false,
  },
  {
    id: 'alrt-2',
    severity: 'P1',
    deviceId: 'def456',
    alias: 'Ram-02',
    kind: 'freeze',
    confidence: 0.81,
    ts: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
    acked: false,
  },
  {
    id: 'alrt-3',
    severity: 'INFO',
    deviceId: 'jkl012',
    alias: 'Ewe-33',
    kind: 'battery_low',
    confidence: 0.75,
    ts: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    acked: true,
  },
];
